#!/usr/bin/env python3
"""Generate the Core Builds Motion live-wallpaper set + Overflight feed.

Unlike the earlier still→zoom approach, these are *procedurally animated*
wallpapers — genuinely moving content generated by ffmpeg, in the Core Builds
§03 palette. This is what a "live wallpaper" is (see Motion/README.md).

Sources (all ffmpeg generators, no external footage):
- gradients  → smooth flowing color fields (spiral / radial / circular)
- cellauto   → elementary cellular automaton, tinted ("circuit" / machine-truth)
- mandelbrot → deep fractal zoom, blurred to compress ("deep zoom")

Outputs:
- Motion/live/*.mp4            silent H.264 1080p 30fps 20s loops
- Motion/live/thumbs/*.jpg     poster frames
- Motion/live/preview.png      contact sheet
- Motion/live-feed.json        Overflight-compatible feed (url_img + url_1080p)

Run:  pip install imageio-ffmpeg && python tools/build_motion_feed.py
"""

import json
import os
import subprocess
import sys

BASE_URL = "https://raw.githubusercontent.com/brevityA/CoreBuildsApps/main/Motion/live"
FPS = 30
DURATION = 20
W, H = 1920, 1080
THUMB_W, THUMB_H = 480, 270

# §03 palette (hex, as ffmpeg colors)
NIGHT = "0x04070f"
CYAN = "0x00e5ff"
SIGNAL = "0x00d4ff"
BUILD_BLUE = "0x4facfe"
VIOLET = "0x8a4890"
EMBER = "0xc03a20"

# ── clips ────────────────────────────────────────────────────────────────
# src = ffmpeg lavfi source string, vf = optional post-filter, crf per clip
CLIPS = [
    dict(slug="spiral-cyan", title="Spiral Cyan",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=spiral:nb_colors=4:"
              f"c0={NIGHT}:c1={CYAN}:c2={BUILD_BLUE}:c3={VIOLET}:"
              f"duration={DURATION}:speed=0.02:seed=111"),
         vf=None, crf=20),
    dict(slug="spiral-ember", title="Spiral Ember",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=spiral:nb_colors=3:"
              f"c0={NIGHT}:c1={EMBER}:c2={VIOLET}:"
              f"duration={DURATION}:speed=0.02:seed=222"),
         vf=None, crf=20),
    dict(slug="radial-cyan", title="Radial Cyan",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=radial:nb_colors=3:"
              f"c0={CYAN}:c1={BUILD_BLUE}:c2={NIGHT}:"
              f"duration={DURATION}:speed=0.02:seed=333"),
         vf=None, crf=20),
    dict(slug="circular-void", title="Circular Void",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=circular:nb_colors=3:"
              f"c0={NIGHT}:c1={SIGNAL}:c2={CYAN}:"
              f"duration={DURATION}:speed=0.02:seed=444"),
         vf=None, crf=20),
    dict(slug="circuit", title="Circuit",
         src=(f"cellauto=size={W}x{H}:rate={FPS}:rule=110:random_fill_ratio=0.18:scroll=1"),
         vf="colorize=hue=190:saturation=0.55:lightness=0",
         crf=23),
    dict(slug="deep-zoom", title="Deep Zoom",
         src=(f"mandelbrot=size={W}x{H}:rate={FPS}:start_scale=2.5:end_scale=0.001:"
              f"maxiter=3000:end_pts={DURATION * FPS}"),
         vf="gblur=sigma=1.2",
         crf=28),
    dict(slug="linear-blue", title="Linear Build Blue",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=linear:nb_colors=3:"
              f"c0={NIGHT}:c1={BUILD_BLUE}:c2={CYAN}:"
              f"duration={DURATION}:speed=0.02:seed=555"),
         vf=None, crf=20),
    dict(slug="square-cyan", title="Square Cyan",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=square:nb_colors=3:"
              f"c0={NIGHT}:c1={CYAN}:c2={SIGNAL}:"
              f"duration={DURATION}:speed=0.02:seed=666"),
         vf=None, crf=20),
    dict(slug="carpet", title="Carpet",
         src=(f"sierpinski=size={W}x{H}:rate={FPS}:seed=42:jump=60:type=carpet"),
         vf="colorize=hue=280:saturation=0.4:lightness=0",
         crf=24),
    dict(slug="spiral-blue", title="Spiral Build Blue",
         src=(f"gradients=size={W}x{H}:rate={FPS}:type=spiral:nb_colors=3:"
              f"c0={NIGHT}:c1={BUILD_BLUE}:c2={CYAN}:"
              f"duration={DURATION}:speed=0.02:seed=777"),
         vf=None, crf=20),
]


def ffmpeg():
    try:
        import imageio_ffmpeg  # type: ignore
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return "ffmpeg"


def build_clip(entry, out):
    cmd = [ffmpeg(), "-y", "-hide_banner", "-loglevel", "error",
           "-f", "lavfi", "-i", entry["src"]]
    if entry["vf"]:
        cmd += ["-vf", entry["vf"]]
    cmd += ["-t", str(DURATION),
            "-c:v", "libx264", "-preset", "slow", "-crf", str(entry["crf"]),
            "-pix_fmt", "yuv420p", "-movflags", "+faststart", "-an", out]
    subprocess.run(cmd, check=True)


def build_thumb(clip, out):
    cmd = [ffmpeg(), "-y", "-hide_banner", "-loglevel", "error",
           "-ss", "1", "-i", clip,
           "-vf", f"scale={THUMB_W}:{THUMB_H}:force_original_aspect_ratio=decrease,"
                  f"pad={THUMB_W}:{THUMB_H}:(ow-iw)/2:(oh-ih)/2:color=black",
           "-frames:v", "1", "-q:v", "3", out]
    subprocess.run(cmd, check=True)


def build_sheet(thumbs, out):
    inputs = []
    for t in thumbs:
        inputs += ["-i", t]
    n = len(thumbs)
    cols, rows = 3, (n + 2) // 3
    cmd = [ffmpeg(), "-y", "-hide_banner", "-loglevel", "error", *inputs,
           "-filter_complex", f"tile={cols}x{rows}", "-frames:v", "1", out]
    subprocess.run(cmd, check=True)


def write_feed():
    feed = []
    for i, e in enumerate(CLIPS):
        mp4 = f"coremotion-live-{i + 1:02d}-{e['slug']}.mp4"
        thumb = f"thumbs/coremotion-live-{i + 1:02d}-{e['slug']}.jpg"
        feed.append({
            "location": "Core Motion",
            "title": e["title"],
            "author": "Core Builds",
            "url_img": f"{BASE_URL}/{thumb}",
            "url_1080p": f"{BASE_URL}/{mp4}",
        })
    with open("Motion/live-feed.json", "w", encoding="utf-8") as f:
        json.dump(feed, f, indent=2)
        f.write("\n")


def main():
    os.makedirs("Motion/live/thumbs", exist_ok=True)
    os.makedirs("Motion/live/preview", exist_ok=True)

    clips = []
    thumbs = []
    for i, e in enumerate(CLIPS):
        mp4 = f"Motion/live/coremotion-live-{i + 1:02d}-{e['slug']}.mp4"
        thumb = f"Motion/live/thumbs/coremotion-live-{i + 1:02d}-{e['slug']}.jpg"
        print(f"building {mp4} ...")
        build_clip(e, mp4)
        clips.append(mp4)
        build_thumb(mp4, thumb)
        thumbs.append(thumb)

    print("building contact sheet ...")
    build_sheet(thumbs, "Motion/live/preview/live-preview.png")
    write_feed()
    print(f"done: {len(clips)} live wallpapers + Motion/live-feed.json")


if __name__ == "__main__":
    sys.exit(main())
